{
"RemeraF";[
    {
            "id":"RF0001",
            "color":"blanca",
            "talle":"m",
            "temporada":"verano",
            "precio":"2000",
            "genero":"femenino",
            "imagen":""
        },
{
        "id":"RF0002",
        "color":"blanca",
        "talle":"s",
        "temporada":"verano",
        "precio":"2500",
        "genero":"femenino",
        "imagen":""
}
    ]
    
}